{% set name = "exspy" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/exspy-{{ version }}.tar.gz
  sha256: c22ab6a3d5785f3194b4aead8f32d11f4161c55b042fe1d270caacfbf26f2397

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - dask-core
    - hyperspy-base >=2.3.0
    - matplotlib-base
    - numexpr
    - numpy
    - pint
    - pooch
    - prettytable
    - requests
    - scipy
    - traits

test:
  imports:
    - exspy
  commands:
    - pip check
    - pytest --pyargs exspy
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  summary: EELS and EDS analysis with the HyperSpy framework
  home: https://github.com/hyperspy/exspy
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://hyperspy.org/exspy
  dev_url: https://github.com/hyperspy/exspy

extra:
  recipe-maintainers:
    - CSSFrancis
    - ericpre
    - francisco-dlp
    - jlaehne
